name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  beyond: 
    git:
      url: https://github.com/Meruya-Techhnology/Beyond.git
      path: beyond

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
